FORMAT: 1A
HOST: http://localhost:3000/api/

# Fetchr

Fetchr api is the backend to the snack courier service from Devs that Deliver

## Users [/users]
### List all users [GET]

+ Response 200 (application/json)

        [
            {
                "user_id": 1,
                "time_created": "2018-09-25T03:27:07.000Z",
                "email_address": "dsafanyuk@email.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 1,
                "phone_number": 9078838372
            },
            {
                "user_id": 8,
                "time_created": "2018-09-25T14:22:11.000Z",
                "email_address": "dsafanyuk@shmoople.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 0,
                "phone_number": 3278838372
            }
        ]
        
### List single user [GET /users/{user_id}]
+ Response 200 (application/json)

        [
            {
                "user_id": 1,
                "time_created": "2018-09-25T03:27:07.000Z",
                "email_address": "dsafanyuk@email.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 1,
                "phone_number": 9078838372
            }
        ]

### Show one user's orders [GET /users/{user_id}/orders]
+ Response 200 (application/json)

        [
            {
                "order_id": 1,
                "customer_id": 1,
                "courier_id": 17,
                "delivery_status": "Pending",
                "time_delivered": "2018-09-25T03:27:07.000Z",
                "time_created": "2018-09-25T03:27:07.000Z",
                "order_total": 20.00
            },
            {
                "order_id": 16,
                "customer_id": 1,
                "courier_id": 13,
                "delivery_status": "Pending",
                "time_delivered": "2018-09-25T03:27:07.000Z",
                "time_created": "2018-09-25T03:27:07.000Z",
                "order_total": 5.00
            }
        ]

### Create a user [POST]
+ Request (application/json)

        {
            "email_address":"dsafanyuk@shmoople.com",
            "password":"notpassword",
            "room_num":"6326",
            "phone_number": 992847463,
            "first_name":"dave",
            "last_name":"safanyuk"
        }

+ Response 200 (application/json)

        {
            "user_id": 1,
            "time_created": "2018-09-25T03:27:07.000Z",
            "email_address": "dsafanyuk@email.com",
            "password": "notpassword",
            "room_num": "6326",
            "is_courier": 0,
            "wallet": 1.23,
            "first_name": "dave",
            "last_name": "safanyuk",
            "is_active": 1,
            "phone_number": 9078838372
        }

### Check for Credit Cards [GET /users/{user_id}/creditCheck]

# Update user [PATCH /users/{user_id}]
+ Response 200 (application/json)

        {
            
        }

# Delete user [DELETE /users/{user_id}]
+ Request (application/json)

        {
            "user_id":"1"
        }

+ Response 200 (application/json)

        {
            "deleted_at":"TIME"
        }

##  Orders [/orders]
### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "order": "1",
                "order_total": "1.00",
                "room_num": "6362",
                "customer": "user_id",
                "courier": NULL,
                "delivery_status": "Pending"
            }
        ]

# List single order [GET /orders/{order_id}]
+ Parameters
    + order_id (number) - ID of the order in the form of an integer
    
+ Response 200 (application/json)

        {
            "order": "1",
            "order_summary": [
                    {
                        "product_name":"Twix",
                        "product_price": "1.00",
                        "quantity": "1"
                    }
            ],
            "order_total": "1.00",
            "room_num": "6362",
            "customer": "dsafanyuk",
            "courier": "user_id",
            "delivery_status": "Pending"
        }
# Create an order [POST /orders/]
+ Request (application/json)

        {
            "user_id": "Favourite programming language?"         
        }

+ Response 200 (application/json)

    + Headers

            Location: /orders/{order_id}

    + Body

            {
                "order_id": "1",
                "created_at": "2015-08-05T08:40:51.620Z"
            }

# Delete an order [DELETE /orders/{order_id}]
+ Request (application/json)

        {
            "user_id":"1"
        }

+ Response 200 (application/json)

        {
            "deleted_at":"TIME"
        }

## Products [/products]

### List all products [GET]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            },
            {
                "product_id": 2,
                "product_name": "Doritos small",
                "price": 1.99,
                "category": "snacks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            }
        ]

### List a single product [GET /products/{product_id}]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
            }
        ]

### Filter products by category [GET /products/filter/{category}]


+ Response 200 (application/json)

        [
            {
                "product_id": 22,
                "product_name": "Eraser",
                "price": 1.12,
                "category": "school_supplies",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 4
            },
            {
                "product_id": 21,
                "product_name": "Pencils",
                "price": 3,
                "category": "school_supplies",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 3
            }
        ]