FORMAT: 1A
HOST: http://localhost:3000/api/

# Fetchr

Fetchr api is the backend to the snack courier service from Devs that Deliver

## Users [/users]
### List all users [GET]

+ Response 200 (application/json)

        [
            {
                "user_id": 1,
                "time_created": "2018-09-25T03:27:07.000Z",
                "email_address": "dsafanyuk@email.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 1,
                "phone_number": 9078838372
            },
            {
                "user_id": 8,
                "time_created": "2018-09-25T14:22:11.000Z",
                "email_address": "dsafanyuk@shmoople.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 0,
                "phone_number": 3278838372
            }
        ]
        
### List single user [GET /users/{user_id}]
+ Response 200 (application/json)

        [
            {
                "user_id": 1,
                "time_created": "2018-09-25T03:27:07.000Z",
                "email_address": "dsafanyuk@email.com",
                "password": "notpassword",
                "room_num": "6326",
                "is_courier": 0,
                "wallet": 1.23,
                "first_name": "dave",
                "last_name": "safanyuk",
                "is_active": 1,
                "phone_number": 9078838372
            }
        ]

### Show one user's orders [GET /users/{user_id}/orders]
+ Parameters
    + user_id (number) - ID of the order in the form of an integer
    
+ Response 200 (application/json)

    [
        {
            "order_id": 1,
            "customer_id": 1,
            "courier_id": 17,
            "delivery_status": "Pending",
            "time_delivered": "2018-09-25T03:27:07.000Z",
            "time_created": "2018-09-25T03:27:07.000Z",
            "order_total": 20.00
        },
        {
            "order_id": 16,
            "customer_id": 1,
            "courier_id": 13,
            "delivery_status": "Pending",
            "time_delivered": "2018-09-25T03:27:07.000Z",
            "time_created": "2018-09-25T03:27:07.000Z",
            "order_total": 5.00
        }
    ]

### Create a user [POST]
+ Request (application/json)

        {
            "email_address":"dsafanyuk@shmoople.com",
            "password":"notpassword",
            "room_num":"6326",
            "phone_number": 992847463,
            "first_name":"dave",
            "last_name":"safanyuk"
        }

+ Response 307 (application/json)

        {
            "user_id": 1,
            "time_created": "2018-09-25T03:27:07.000Z",
            "email_address": "dsafanyuk@email.com",
            "password": "notpassword",
            "room_num": "6326",
            "is_courier": 0,
            "wallet": 1.23,
            "first_name": "dave",
            "last_name": "safanyuk",
            "is_active": 1,
            "phone_number": 9078838372
        }

### Login [POST /users/login]
+ Request(application/json)

        {
            "email_address": lolokay@partycentral.com,
            "password": "hahagitrekt"
        }

+ Response 200 (application/json)

        {
            login token
        }

### Check for credit cards [GET /users/{user_id}/creditCheck]
+ Parameters
    + user_id (number) - ID of the order in the form of an integer

# Update user [PATCH /users/{user_id}]
+ Response 200 (application/json)

        {
            
        }

# Delete user [DELETE /users/{user_id}]
+ Request (application/json)

        {
            "user_id":"1"
        }

+ Response 200 (application/json)

        {
            "deleted_at":"TIME"
        }


### List user's favorites [GET /users/{user_id}/favorites]
+ Parameters
    + user_id (number) - ID of the order in the form of an integer

+ Response 200 (application/json)

        [
            {
                "user_id": 1,
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
            },
            {
                "user_id": 1,
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
            }
        ]


### Favorite a product [POST /users/favorite]

+ Request (application/json)

        {
            "user_id": 1,
            "product_id": 1
        }

+ Response 200 (application/json)


### Unfavorite a product [DELETE /users/unfavorite]

+ Request (application/json)

        {
            "user_id": 1,
            "product_id": 1
        }
        

+ Response 200 (application/json)


##  Orders [/orders]
### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "order_id": 1,
                "customer_id": 1,
                "courier_id": 17,
                "delivery_status": "Pending",
                "time_delivered": "2018-09-25T03:27:07.000Z",
                "time_created": "2018-09-25T03:27:07.000Z",
                "order_total": 20.00
            }
        ]

# List single order [GET /orders/{order_id}]
+ Parameters
    + order_id (number) - ID of the order in the form of an integer
    
+ Response 200 (application/json)

        {
            "order_id": 1,
            "customer_id": 1,
            "courier_id": 17,
            "delivery_status": "Pending",
            "time_delivered": "2018-09-25T03:27:07.000Z",
            "time_created": "2018-09-25T03:27:07.000Z",
            "order_total": 20.00
        }
# Create an order [POST /orders/]

+ Response 201 (application/json)

            {
                "order created for id 1"
            }


# Show order summary [GET /orders/{order_id}/summary]
+ Parameters
    + order_id (number) - ID of the order in the form of an integer

        {
            "product_name": "Popsicle",
            "quantity": "700",
            "price": 1500,
            "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
        }

## Products [/products]

### List all products [GET]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            },
            {
                "product_id": 2,
                "product_name": "Doritos small",
                "price": 1.99,
                "category": "snacks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            }
        ]

### List a single product [GET /products/{product_id}]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
            }
        ]

### Filter products by category [GET /products/filter/{category}]


+ Response 200 (application/json)
        [
            {
                "product_id": 22,
                "product_name": "Eraser",
                "price": 1.12,
                "category": "school_supplies",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 4
            },
            {
                "product_id": 21,
                "product_name": "Pencils",
                "price": 3,
                "category": "school_supplies",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 3
            }
        ]
        {
            "deleted_at":"TIME"
        }

## Products [/products]

### List all products [GET]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            },
            {
                "product_id": 2,
                "product_name": "Doritos small",
                "price": 1.99,
                "category": "snacks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
                "total_sold": 100.00
            }
        ]

### List a single product [GET /products/{product_id}]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "product_name": "Arizona Tea",
                "price": 0.99,
                "category": "drinks",
                "product_url": "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg"
            }
        ]
